### ISSUE TITLE
Tutorial in Docs not working

### ISSUE THREAD

**Issue by jcope2013** [caribou/caribou-docs#2]
http://caribou.github.io/caribou/docs/tutorial.html

I am going through this step by step, and when I get to step 7
I don't get the Edit Button to add new slides to the collection, there is no button there for me to click

**Comment by prismofeverything** [comment]
Hello Josh,

Are you sure you have saved the presentation first?  I went through the steps and currently you have to save the presentation before you can add slides to the collection.  

Also, the admin has moved on since the tutorial was made, it may not be exactly the same as in the pictures (in particular, page editing has improved greatly.)  Though all of the same elements are present.

**Comment by jcope2013** [comment]
Yes I saved presentation first, Im just not getting the blue edit button next so it just says Slides collection 0 Items 

so I go directly into the Slides model, create a new slide and attach it to the MOUNTAINS presentation using the dropdown menu, I then go back into Presentation, still no edit button but it tells me there is 1 slide

so I go on do the rest of the tutorial and try to run it and it constantly crashes and points back to this line inside the presentation controller in the site/src/pictograph/controllers/home.clj file

```
(render (assoc request
          :presentation presentation))))
```

**Comment by quile** [comment]
Hey Josh, thanks for getting in touch.

Can you tell us: 
- What OS you're using
- What browser you're testing with
- What JDK version you have (if you know... usually the output of
  java -version
  will tell you)

It sounds to me like it might be a browser issue, and perhaps that has resulted in your having some bad data in your DB.

Cheers!

**Comment by prismofeverything** [comment]
Also, what is the stacktrace?  I suspect this may be an issue with the reciprocal name, but not sure.
